package com.antimoney.boot.model;

public class amlInternalControlRegulation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.submit_year
     *
     * @mbggenerated
     */
    private String submitYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.sys_grade
     *
     * @mbggenerated
     */
    private String sysGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.material_type
     *
     * @mbggenerated
     */
    private String materialType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.report_table_ids
     *
     * @mbggenerated
     */
    private String reportTableIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.enclosed_documents
     *
     * @mbggenerated
     */
    private String enclosedDocuments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.process_state
     *
     * @mbggenerated
     */
    private String processState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.approver_id
     *
     * @mbggenerated
     */
    private String approverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.system_grade
     *
     * @mbggenerated
     */
    private String systemGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.approver_grade
     *
     * @mbggenerated
     */
    private String approverGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.approve_common
     *
     * @mbggenerated
     */
    private String approveCommon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_submit_log_and_material.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.id
     *
     * @return the value of aml_submit_log_and_material.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.id
     *
     * @param id the value for aml_submit_log_and_material.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.gmt_created
     *
     * @return the value of aml_submit_log_and_material.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.gmt_created
     *
     * @param gmtCreated the value for aml_submit_log_and_material.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.gmt_creator
     *
     * @return the value of aml_submit_log_and_material.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.gmt_creator
     *
     * @param gmtCreator the value for aml_submit_log_and_material.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.gmt_updated
     *
     * @return the value of aml_submit_log_and_material.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.gmt_updated
     *
     * @param gmtUpdated the value for aml_submit_log_and_material.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.gmt_updator
     *
     * @return the value of aml_submit_log_and_material.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.gmt_updator
     *
     * @param gmtUpdator the value for aml_submit_log_and_material.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.is_deleted
     *
     * @return the value of aml_submit_log_and_material.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.is_deleted
     *
     * @param isDeleted the value for aml_submit_log_and_material.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.submit_year
     *
     * @return the value of aml_submit_log_and_material.submit_year
     *
     * @mbggenerated
     */
    public String getSubmitYear() {
        return submitYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.submit_year
     *
     * @param submitYear the value for aml_submit_log_and_material.submit_year
     *
     * @mbggenerated
     */
    public void setSubmitYear(String submitYear) {
        this.submitYear = submitYear == null ? null : submitYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.sys_grade
     *
     * @return the value of aml_submit_log_and_material.sys_grade
     *
     * @mbggenerated
     */
    public String getSysGrade() {
        return sysGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.sys_grade
     *
     * @param sysGrade the value for aml_submit_log_and_material.sys_grade
     *
     * @mbggenerated
     */
    public void setSysGrade(String sysGrade) {
        this.sysGrade = sysGrade == null ? null : sysGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.org_id
     *
     * @return the value of aml_submit_log_and_material.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.org_id
     *
     * @param orgId the value for aml_submit_log_and_material.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.material_type
     *
     * @return the value of aml_submit_log_and_material.material_type
     *
     * @mbggenerated
     */
    public String getMaterialType() {
        return materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.material_type
     *
     * @param materialType the value for aml_submit_log_and_material.material_type
     *
     * @mbggenerated
     */
    public void setMaterialType(String materialType) {
        this.materialType = materialType == null ? null : materialType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.report_table_ids
     *
     * @return the value of aml_submit_log_and_material.report_table_ids
     *
     * @mbggenerated
     */
    public String getReportTableIds() {
        return reportTableIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.report_table_ids
     *
     * @param reportTableIds the value for aml_submit_log_and_material.report_table_ids
     *
     * @mbggenerated
     */
    public void setReportTableIds(String reportTableIds) {
        this.reportTableIds = reportTableIds == null ? null : reportTableIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.enclosed_documents
     *
     * @return the value of aml_submit_log_and_material.enclosed_documents
     *
     * @mbggenerated
     */
    public String getEnclosedDocuments() {
        return enclosedDocuments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.enclosed_documents
     *
     * @param enclosedDocuments the value for aml_submit_log_and_material.enclosed_documents
     *
     * @mbggenerated
     */
    public void setEnclosedDocuments(String enclosedDocuments) {
        this.enclosedDocuments = enclosedDocuments == null ? null : enclosedDocuments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.process_state
     *
     * @return the value of aml_submit_log_and_material.process_state
     *
     * @mbggenerated
     */
    public String getProcessState() {
        return processState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.process_state
     *
     * @param processState the value for aml_submit_log_and_material.process_state
     *
     * @mbggenerated
     */
    public void setProcessState(String processState) {
        this.processState = processState == null ? null : processState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.approver_id
     *
     * @return the value of aml_submit_log_and_material.approver_id
     *
     * @mbggenerated
     */
    public String getApproverId() {
        return approverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.approver_id
     *
     * @param approverId the value for aml_submit_log_and_material.approver_id
     *
     * @mbggenerated
     */
    public void setApproverId(String approverId) {
        this.approverId = approverId == null ? null : approverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.system_grade
     *
     * @return the value of aml_submit_log_and_material.system_grade
     *
     * @mbggenerated
     */
    public String getSystemGrade() {
        return systemGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.system_grade
     *
     * @param systemGrade the value for aml_submit_log_and_material.system_grade
     *
     * @mbggenerated
     */
    public void setSystemGrade(String systemGrade) {
        this.systemGrade = systemGrade == null ? null : systemGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.approver_grade
     *
     * @return the value of aml_submit_log_and_material.approver_grade
     *
     * @mbggenerated
     */
    public String getApproverGrade() {
        return approverGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.approver_grade
     *
     * @param approverGrade the value for aml_submit_log_and_material.approver_grade
     *
     * @mbggenerated
     */
    public void setApproverGrade(String approverGrade) {
        this.approverGrade = approverGrade == null ? null : approverGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.approve_common
     *
     * @return the value of aml_submit_log_and_material.approve_common
     *
     * @mbggenerated
     */
    public String getApproveCommon() {
        return approveCommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.approve_common
     *
     * @param approveCommon the value for aml_submit_log_and_material.approve_common
     *
     * @mbggenerated
     */
    public void setApproveCommon(String approveCommon) {
        this.approveCommon = approveCommon == null ? null : approveCommon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_submit_log_and_material.remark
     *
     * @return the value of aml_submit_log_and_material.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_submit_log_and_material.remark
     *
     * @param remark the value for aml_submit_log_and_material.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}