package com.antimoney.boot.model;

public class AttachmentType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_type.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_type.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_type.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_type.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_type.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_type.material_type_id
     *
     * @mbggenerated
     */
    private Integer materialTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_type.attachment_type_name
     *
     * @mbggenerated
     */
    private String attachmentTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_type.id
     *
     * @return the value of aml_attachment_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_type.id
     *
     * @param id the value for aml_attachment_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_type.gmt_created
     *
     * @return the value of aml_attachment_type.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_type.gmt_created
     *
     * @param gmtCreated the value for aml_attachment_type.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_type.gmt_creator
     *
     * @return the value of aml_attachment_type.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_type.gmt_creator
     *
     * @param gmtCreator the value for aml_attachment_type.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_type.gmt_updated
     *
     * @return the value of aml_attachment_type.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_type.gmt_updated
     *
     * @param gmtUpdated the value for aml_attachment_type.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_type.gmt_updator
     *
     * @return the value of aml_attachment_type.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_type.gmt_updator
     *
     * @param gmtUpdator the value for aml_attachment_type.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_type.is_deleted
     *
     * @return the value of aml_attachment_type.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_type.is_deleted
     *
     * @param isDeleted the value for aml_attachment_type.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_type.material_type_id
     *
     * @return the value of aml_attachment_type.material_type_id
     *
     * @mbggenerated
     */
    public Integer getMaterialTypeId() {
        return materialTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_type.material_type_id
     *
     * @param materialTypeId the value for aml_attachment_type.material_type_id
     *
     * @mbggenerated
     */
    public void setMaterialTypeId(Integer materialTypeId) {
        this.materialTypeId = materialTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_type.attachment_type_name
     *
     * @return the value of aml_attachment_type.attachment_type_name
     *
     * @mbggenerated
     */
    public String getAttachmentTypeName() {
        return attachmentTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_type.attachment_type_name
     *
     * @param attachmentTypeName the value for aml_attachment_type.attachment_type_name
     *
     * @mbggenerated
     */
    public void setAttachmentTypeName(String attachmentTypeName) {
        this.attachmentTypeName = attachmentTypeName == null ? null : attachmentTypeName.trim();
    }
}