package com.antimoney.boot.model;

public class AttachmentLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.org_material_log_id
     *
     * @mbggenerated
     */
    private Integer orgMaterialLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.origin_file_name
     *
     * @mbggenerated
     */
    private String originFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.attachment_type_id
     *
     * @mbggenerated
     */
    private Integer attachmentTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_attachment_log.disk_url
     *
     * @mbggenerated
     */
    private String diskUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.id
     *
     * @return the value of aml_attachment_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.id
     *
     * @param id the value for aml_attachment_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.gmt_created
     *
     * @return the value of aml_attachment_log.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.gmt_created
     *
     * @param gmtCreated the value for aml_attachment_log.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.gmt_creator
     *
     * @return the value of aml_attachment_log.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.gmt_creator
     *
     * @param gmtCreator the value for aml_attachment_log.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.gmt_updated
     *
     * @return the value of aml_attachment_log.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.gmt_updated
     *
     * @param gmtUpdated the value for aml_attachment_log.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.gmt_updator
     *
     * @return the value of aml_attachment_log.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.gmt_updator
     *
     * @param gmtUpdator the value for aml_attachment_log.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.is_deleted
     *
     * @return the value of aml_attachment_log.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.is_deleted
     *
     * @param isDeleted the value for aml_attachment_log.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.org_material_log_id
     *
     * @return the value of aml_attachment_log.org_material_log_id
     *
     * @mbggenerated
     */
    public Integer getOrgMaterialLogId() {
        return orgMaterialLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.org_material_log_id
     *
     * @param orgMaterialLogId the value for aml_attachment_log.org_material_log_id
     *
     * @mbggenerated
     */
    public void setOrgMaterialLogId(Integer orgMaterialLogId) {
        this.orgMaterialLogId = orgMaterialLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.origin_file_name
     *
     * @return the value of aml_attachment_log.origin_file_name
     *
     * @mbggenerated
     */
    public String getOriginFileName() {
        return originFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.origin_file_name
     *
     * @param originFileName the value for aml_attachment_log.origin_file_name
     *
     * @mbggenerated
     */
    public void setOriginFileName(String originFileName) {
        this.originFileName = originFileName == null ? null : originFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.attachment_type_id
     *
     * @return the value of aml_attachment_log.attachment_type_id
     *
     * @mbggenerated
     */
    public Integer getAttachmentTypeId() {
        return attachmentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.attachment_type_id
     *
     * @param attachmentTypeId the value for aml_attachment_log.attachment_type_id
     *
     * @mbggenerated
     */
    public void setAttachmentTypeId(Integer attachmentTypeId) {
        this.attachmentTypeId = attachmentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_attachment_log.disk_url
     *
     * @return the value of aml_attachment_log.disk_url
     *
     * @mbggenerated
     */
    public String getDiskUrl() {
        return diskUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_attachment_log.disk_url
     *
     * @param diskUrl the value for aml_attachment_log.disk_url
     *
     * @mbggenerated
     */
    public void setDiskUrl(String diskUrl) {
        this.diskUrl = diskUrl == null ? null : diskUrl.trim();
    }
}