package com.antimoney.boot.model;

public class LeadingGroupConference {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.submit_year
     *
     * @mbggenerated
     */
    private String submitYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.sys_grade
     *
     * @mbggenerated
     */
    private String sysGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.org_name_SI
     *
     * @mbggenerated
     */
    private String orgNameSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.conference_time_DI
     *
     * @mbggenerated
     */
    private String conferenceTimeDi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.conference_participants_SI
     *
     * @mbggenerated
     */
    private String conferenceParticipantsSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.conference_location_SI
     *
     * @mbggenerated
     */
    private String conferenceLocationSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.conference_content_MI
     *
     * @mbggenerated
     */
    private String conferenceContentMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.task_implementation_MI
     *
     * @mbggenerated
     */
    private String taskImplementationMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_conference.remark_MI
     *
     * @mbggenerated
     */
    private String remarkMi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.id
     *
     * @return the value of aml_leading_group_conference.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.id
     *
     * @param id the value for aml_leading_group_conference.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.gmt_created
     *
     * @return the value of aml_leading_group_conference.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.gmt_created
     *
     * @param gmtCreated the value for aml_leading_group_conference.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.gmt_creator
     *
     * @return the value of aml_leading_group_conference.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.gmt_creator
     *
     * @param gmtCreator the value for aml_leading_group_conference.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.gmt_updated
     *
     * @return the value of aml_leading_group_conference.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.gmt_updated
     *
     * @param gmtUpdated the value for aml_leading_group_conference.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.gmt_updator
     *
     * @return the value of aml_leading_group_conference.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.gmt_updator
     *
     * @param gmtUpdator the value for aml_leading_group_conference.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.is_deleted
     *
     * @return the value of aml_leading_group_conference.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.is_deleted
     *
     * @param isDeleted the value for aml_leading_group_conference.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.submit_year
     *
     * @return the value of aml_leading_group_conference.submit_year
     *
     * @mbggenerated
     */
    public String getSubmitYear() {
        return submitYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.submit_year
     *
     * @param submitYear the value for aml_leading_group_conference.submit_year
     *
     * @mbggenerated
     */
    public void setSubmitYear(String submitYear) {
        this.submitYear = submitYear == null ? null : submitYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.sys_grade
     *
     * @return the value of aml_leading_group_conference.sys_grade
     *
     * @mbggenerated
     */
    public String getSysGrade() {
        return sysGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.sys_grade
     *
     * @param sysGrade the value for aml_leading_group_conference.sys_grade
     *
     * @mbggenerated
     */
    public void setSysGrade(String sysGrade) {
        this.sysGrade = sysGrade == null ? null : sysGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.org_id
     *
     * @return the value of aml_leading_group_conference.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.org_id
     *
     * @param orgId the value for aml_leading_group_conference.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.org_name_SI
     *
     * @return the value of aml_leading_group_conference.org_name_SI
     *
     * @mbggenerated
     */
    public String getOrgNameSi() {
        return orgNameSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.org_name_SI
     *
     * @param orgNameSi the value for aml_leading_group_conference.org_name_SI
     *
     * @mbggenerated
     */
    public void setOrgNameSi(String orgNameSi) {
        this.orgNameSi = orgNameSi == null ? null : orgNameSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.conference_time_DI
     *
     * @return the value of aml_leading_group_conference.conference_time_DI
     *
     * @mbggenerated
     */
    public String getConferenceTimeDi() {
        return conferenceTimeDi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.conference_time_DI
     *
     * @param conferenceTimeDi the value for aml_leading_group_conference.conference_time_DI
     *
     * @mbggenerated
     */
    public void setConferenceTimeDi(String conferenceTimeDi) {
        this.conferenceTimeDi = conferenceTimeDi == null ? null : conferenceTimeDi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.conference_participants_SI
     *
     * @return the value of aml_leading_group_conference.conference_participants_SI
     *
     * @mbggenerated
     */
    public String getConferenceParticipantsSi() {
        return conferenceParticipantsSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.conference_participants_SI
     *
     * @param conferenceParticipantsSi the value for aml_leading_group_conference.conference_participants_SI
     *
     * @mbggenerated
     */
    public void setConferenceParticipantsSi(String conferenceParticipantsSi) {
        this.conferenceParticipantsSi = conferenceParticipantsSi == null ? null : conferenceParticipantsSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.conference_location_SI
     *
     * @return the value of aml_leading_group_conference.conference_location_SI
     *
     * @mbggenerated
     */
    public String getConferenceLocationSi() {
        return conferenceLocationSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.conference_location_SI
     *
     * @param conferenceLocationSi the value for aml_leading_group_conference.conference_location_SI
     *
     * @mbggenerated
     */
    public void setConferenceLocationSi(String conferenceLocationSi) {
        this.conferenceLocationSi = conferenceLocationSi == null ? null : conferenceLocationSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.conference_content_MI
     *
     * @return the value of aml_leading_group_conference.conference_content_MI
     *
     * @mbggenerated
     */
    public String getConferenceContentMi() {
        return conferenceContentMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.conference_content_MI
     *
     * @param conferenceContentMi the value for aml_leading_group_conference.conference_content_MI
     *
     * @mbggenerated
     */
    public void setConferenceContentMi(String conferenceContentMi) {
        this.conferenceContentMi = conferenceContentMi == null ? null : conferenceContentMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.task_implementation_MI
     *
     * @return the value of aml_leading_group_conference.task_implementation_MI
     *
     * @mbggenerated
     */
    public String getTaskImplementationMi() {
        return taskImplementationMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.task_implementation_MI
     *
     * @param taskImplementationMi the value for aml_leading_group_conference.task_implementation_MI
     *
     * @mbggenerated
     */
    public void setTaskImplementationMi(String taskImplementationMi) {
        this.taskImplementationMi = taskImplementationMi == null ? null : taskImplementationMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_conference.remark_MI
     *
     * @return the value of aml_leading_group_conference.remark_MI
     *
     * @mbggenerated
     */
    public String getRemarkMi() {
        return remarkMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_conference.remark_MI
     *
     * @param remarkMi the value for aml_leading_group_conference.remark_MI
     *
     * @mbggenerated
     */
    public void setRemarkMi(String remarkMi) {
        this.remarkMi = remarkMi == null ? null : remarkMi.trim();
    }
}