package com.antimoney.boot.model;

public class LeadingGroupFoundation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.submit_year
     *
     * @mbggenerated
     */
    private String submitYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.sys_grade
     *
     * @mbggenerated
     */
    private String sysGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.org_name_SI
     *
     * @mbggenerated
     */
    private String orgNameSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.member_name_SI
     *
     * @mbggenerated
     */
    private String memberNameSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.member_department_SI
     *
     * @mbggenerated
     */
    private String memberDepartmentSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.political_principalship_SI
     *
     * @mbggenerated
     */
    private String politicalPrincipalshipSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.internal_principalship_SI
     *
     * @mbggenerated
     */
    private String internalPrincipalshipSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.political_principalship_time_DI
     *
     * @mbggenerated
     */
    private String politicalPrincipalshipTimeDi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.internal_principalship_time_DI
     *
     * @mbggenerated
     */
    private String internalPrincipalshipTimeDi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_leading_group_foundation.remark_MI
     *
     * @mbggenerated
     */
    private String remarkMi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.id
     *
     * @return the value of aml_leading_group_foundation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.id
     *
     * @param id the value for aml_leading_group_foundation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.gmt_created
     *
     * @return the value of aml_leading_group_foundation.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.gmt_created
     *
     * @param gmtCreated the value for aml_leading_group_foundation.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.gmt_creator
     *
     * @return the value of aml_leading_group_foundation.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.gmt_creator
     *
     * @param gmtCreator the value for aml_leading_group_foundation.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.gmt_updated
     *
     * @return the value of aml_leading_group_foundation.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.gmt_updated
     *
     * @param gmtUpdated the value for aml_leading_group_foundation.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.gmt_updator
     *
     * @return the value of aml_leading_group_foundation.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.gmt_updator
     *
     * @param gmtUpdator the value for aml_leading_group_foundation.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.is_deleted
     *
     * @return the value of aml_leading_group_foundation.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.is_deleted
     *
     * @param isDeleted the value for aml_leading_group_foundation.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.submit_year
     *
     * @return the value of aml_leading_group_foundation.submit_year
     *
     * @mbggenerated
     */
    public String getSubmitYear() {
        return submitYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.submit_year
     *
     * @param submitYear the value for aml_leading_group_foundation.submit_year
     *
     * @mbggenerated
     */
    public void setSubmitYear(String submitYear) {
        this.submitYear = submitYear == null ? null : submitYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.sys_grade
     *
     * @return the value of aml_leading_group_foundation.sys_grade
     *
     * @mbggenerated
     */
    public String getSysGrade() {
        return sysGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.sys_grade
     *
     * @param sysGrade the value for aml_leading_group_foundation.sys_grade
     *
     * @mbggenerated
     */
    public void setSysGrade(String sysGrade) {
        this.sysGrade = sysGrade == null ? null : sysGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.org_id
     *
     * @return the value of aml_leading_group_foundation.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.org_id
     *
     * @param orgId the value for aml_leading_group_foundation.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.org_name_SI
     *
     * @return the value of aml_leading_group_foundation.org_name_SI
     *
     * @mbggenerated
     */
    public String getOrgNameSi() {
        return orgNameSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.org_name_SI
     *
     * @param orgNameSi the value for aml_leading_group_foundation.org_name_SI
     *
     * @mbggenerated
     */
    public void setOrgNameSi(String orgNameSi) {
        this.orgNameSi = orgNameSi == null ? null : orgNameSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.member_name_SI
     *
     * @return the value of aml_leading_group_foundation.member_name_SI
     *
     * @mbggenerated
     */
    public String getMemberNameSi() {
        return memberNameSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.member_name_SI
     *
     * @param memberNameSi the value for aml_leading_group_foundation.member_name_SI
     *
     * @mbggenerated
     */
    public void setMemberNameSi(String memberNameSi) {
        this.memberNameSi = memberNameSi == null ? null : memberNameSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.member_department_SI
     *
     * @return the value of aml_leading_group_foundation.member_department_SI
     *
     * @mbggenerated
     */
    public String getMemberDepartmentSi() {
        return memberDepartmentSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.member_department_SI
     *
     * @param memberDepartmentSi the value for aml_leading_group_foundation.member_department_SI
     *
     * @mbggenerated
     */
    public void setMemberDepartmentSi(String memberDepartmentSi) {
        this.memberDepartmentSi = memberDepartmentSi == null ? null : memberDepartmentSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.political_principalship_SI
     *
     * @return the value of aml_leading_group_foundation.political_principalship_SI
     *
     * @mbggenerated
     */
    public String getPoliticalPrincipalshipSi() {
        return politicalPrincipalshipSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.political_principalship_SI
     *
     * @param politicalPrincipalshipSi the value for aml_leading_group_foundation.political_principalship_SI
     *
     * @mbggenerated
     */
    public void setPoliticalPrincipalshipSi(String politicalPrincipalshipSi) {
        this.politicalPrincipalshipSi = politicalPrincipalshipSi == null ? null : politicalPrincipalshipSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.internal_principalship_SI
     *
     * @return the value of aml_leading_group_foundation.internal_principalship_SI
     *
     * @mbggenerated
     */
    public String getInternalPrincipalshipSi() {
        return internalPrincipalshipSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.internal_principalship_SI
     *
     * @param internalPrincipalshipSi the value for aml_leading_group_foundation.internal_principalship_SI
     *
     * @mbggenerated
     */
    public void setInternalPrincipalshipSi(String internalPrincipalshipSi) {
        this.internalPrincipalshipSi = internalPrincipalshipSi == null ? null : internalPrincipalshipSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.political_principalship_time_DI
     *
     * @return the value of aml_leading_group_foundation.political_principalship_time_DI
     *
     * @mbggenerated
     */
    public String getPoliticalPrincipalshipTimeDi() {
        return politicalPrincipalshipTimeDi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.political_principalship_time_DI
     *
     * @param politicalPrincipalshipTimeDi the value for aml_leading_group_foundation.political_principalship_time_DI
     *
     * @mbggenerated
     */
    public void setPoliticalPrincipalshipTimeDi(String politicalPrincipalshipTimeDi) {
        this.politicalPrincipalshipTimeDi = politicalPrincipalshipTimeDi == null ? null : politicalPrincipalshipTimeDi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.internal_principalship_time_DI
     *
     * @return the value of aml_leading_group_foundation.internal_principalship_time_DI
     *
     * @mbggenerated
     */
    public String getInternalPrincipalshipTimeDi() {
        return internalPrincipalshipTimeDi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.internal_principalship_time_DI
     *
     * @param internalPrincipalshipTimeDi the value for aml_leading_group_foundation.internal_principalship_time_DI
     *
     * @mbggenerated
     */
    public void setInternalPrincipalshipTimeDi(String internalPrincipalshipTimeDi) {
        this.internalPrincipalshipTimeDi = internalPrincipalshipTimeDi == null ? null : internalPrincipalshipTimeDi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_leading_group_foundation.remark_MI
     *
     * @return the value of aml_leading_group_foundation.remark_MI
     *
     * @mbggenerated
     */
    public String getRemarkMi() {
        return remarkMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_leading_group_foundation.remark_MI
     *
     * @param remarkMi the value for aml_leading_group_foundation.remark_MI
     *
     * @mbggenerated
     */
    public void setRemarkMi(String remarkMi) {
        this.remarkMi = remarkMi == null ? null : remarkMi.trim();
    }
}