package com.antimoney.boot.model;

public class MaterialType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.evaluation_id
     *
     * @mbggenerated
     */
    private Integer evaluationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.score_weight
     *
     * @mbggenerated
     */
    private Integer scoreWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_material_type.score_regulation
     *
     * @mbggenerated
     */
    private String scoreRegulation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.id
     *
     * @return the value of aml_material_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.id
     *
     * @param id the value for aml_material_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.gmt_created
     *
     * @return the value of aml_material_type.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.gmt_created
     *
     * @param gmtCreated the value for aml_material_type.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.gmt_creator
     *
     * @return the value of aml_material_type.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.gmt_creator
     *
     * @param gmtCreator the value for aml_material_type.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.gmt_updated
     *
     * @return the value of aml_material_type.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.gmt_updated
     *
     * @param gmtUpdated the value for aml_material_type.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.gmt_updator
     *
     * @return the value of aml_material_type.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.gmt_updator
     *
     * @param gmtUpdator the value for aml_material_type.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.is_deleted
     *
     * @return the value of aml_material_type.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.is_deleted
     *
     * @param isDeleted the value for aml_material_type.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.type_name
     *
     * @return the value of aml_material_type.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.type_name
     *
     * @param typeName the value for aml_material_type.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.evaluation_id
     *
     * @return the value of aml_material_type.evaluation_id
     *
     * @mbggenerated
     */
    public Integer getEvaluationId() {
        return evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.evaluation_id
     *
     * @param evaluationId the value for aml_material_type.evaluation_id
     *
     * @mbggenerated
     */
    public void setEvaluationId(Integer evaluationId) {
        this.evaluationId = evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.score_weight
     *
     * @return the value of aml_material_type.score_weight
     *
     * @mbggenerated
     */
    public Integer getScoreWeight() {
        return scoreWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.score_weight
     *
     * @param scoreWeight the value for aml_material_type.score_weight
     *
     * @mbggenerated
     */
    public void setScoreWeight(Integer scoreWeight) {
        this.scoreWeight = scoreWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_material_type.score_regulation
     *
     * @return the value of aml_material_type.score_regulation
     *
     * @mbggenerated
     */
    public String getScoreRegulation() {
        return scoreRegulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_material_type.score_regulation
     *
     * @param scoreRegulation the value for aml_material_type.score_regulation
     *
     * @mbggenerated
     */
    public void setScoreRegulation(String scoreRegulation) {
        this.scoreRegulation = scoreRegulation == null ? null : scoreRegulation.trim();
    }
}