package com.antimoney.boot.model;

public class OrgMaterialLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.material_type_id
     *
     * @mbggenerated
     */
    private Integer materialTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.submit_year
     *
     * @mbggenerated
     */
    private String submitYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.process_state
     *
     * @mbggenerated
     */
    private String processState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.system_grade
     *
     * @mbggenerated
     */
    private String systemGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.self_grade
     *
     * @mbggenerated
     */
    private String selfGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.approver_grade
     *
     * @mbggenerated
     */
    private String approverGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_log.approve_comment
     *
     * @mbggenerated
     */
    private String approveComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.id
     *
     * @return the value of aml_org_material_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.id
     *
     * @param id the value for aml_org_material_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.gmt_created
     *
     * @return the value of aml_org_material_log.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.gmt_created
     *
     * @param gmtCreated the value for aml_org_material_log.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.gmt_creator
     *
     * @return the value of aml_org_material_log.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.gmt_creator
     *
     * @param gmtCreator the value for aml_org_material_log.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.gmt_updated
     *
     * @return the value of aml_org_material_log.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.gmt_updated
     *
     * @param gmtUpdated the value for aml_org_material_log.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.gmt_updator
     *
     * @return the value of aml_org_material_log.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.gmt_updator
     *
     * @param gmtUpdator the value for aml_org_material_log.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.is_deleted
     *
     * @return the value of aml_org_material_log.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.is_deleted
     *
     * @param isDeleted the value for aml_org_material_log.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.material_type_id
     *
     * @return the value of aml_org_material_log.material_type_id
     *
     * @mbggenerated
     */
    public Integer getMaterialTypeId() {
        return materialTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.material_type_id
     *
     * @param materialTypeId the value for aml_org_material_log.material_type_id
     *
     * @mbggenerated
     */
    public void setMaterialTypeId(Integer materialTypeId) {
        this.materialTypeId = materialTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.org_id
     *
     * @return the value of aml_org_material_log.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.org_id
     *
     * @param orgId the value for aml_org_material_log.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.submit_year
     *
     * @return the value of aml_org_material_log.submit_year
     *
     * @mbggenerated
     */
    public String getSubmitYear() {
        return submitYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.submit_year
     *
     * @param submitYear the value for aml_org_material_log.submit_year
     *
     * @mbggenerated
     */
    public void setSubmitYear(String submitYear) {
        this.submitYear = submitYear == null ? null : submitYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.process_state
     *
     * @return the value of aml_org_material_log.process_state
     *
     * @mbggenerated
     */
    public String getProcessState() {
        return processState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.process_state
     *
     * @param processState the value for aml_org_material_log.process_state
     *
     * @mbggenerated
     */
    public void setProcessState(String processState) {
        this.processState = processState == null ? null : processState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.system_grade
     *
     * @return the value of aml_org_material_log.system_grade
     *
     * @mbggenerated
     */
    public String getSystemGrade() {
        return systemGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.system_grade
     *
     * @param systemGrade the value for aml_org_material_log.system_grade
     *
     * @mbggenerated
     */
    public void setSystemGrade(String systemGrade) {
        this.systemGrade = systemGrade == null ? null : systemGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.self_grade
     *
     * @return the value of aml_org_material_log.self_grade
     *
     * @mbggenerated
     */
    public String getSelfGrade() {
        return selfGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.self_grade
     *
     * @param selfGrade the value for aml_org_material_log.self_grade
     *
     * @mbggenerated
     */
    public void setSelfGrade(String selfGrade) {
        this.selfGrade = selfGrade == null ? null : selfGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.approver_grade
     *
     * @return the value of aml_org_material_log.approver_grade
     *
     * @mbggenerated
     */
    public String getApproverGrade() {
        return approverGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.approver_grade
     *
     * @param approverGrade the value for aml_org_material_log.approver_grade
     *
     * @mbggenerated
     */
    public void setApproverGrade(String approverGrade) {
        this.approverGrade = approverGrade == null ? null : approverGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_log.approve_comment
     *
     * @return the value of aml_org_material_log.approve_comment
     *
     * @mbggenerated
     */
    public String getApproveComment() {
        return approveComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_log.approve_comment
     *
     * @param approveComment the value for aml_org_material_log.approve_comment
     *
     * @mbggenerated
     */
    public void setApproveComment(String approveComment) {
        this.approveComment = approveComment == null ? null : approveComment.trim();
    }
}