package com.antimoney.boot.model;

public class OrgMaterialNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_node.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_node.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_node.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_node.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_node.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_node.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_node.org_material_log_id
     *
     * @mbggenerated
     */
    private Integer orgMaterialLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_node.material_node_id
     *
     * @mbggenerated
     */
    private Integer materialNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_org_material_node.node_status
     *
     * @mbggenerated
     */
    private String nodeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_node.id
     *
     * @return the value of aml_org_material_node.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_node.id
     *
     * @param id the value for aml_org_material_node.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_node.gmt_created
     *
     * @return the value of aml_org_material_node.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_node.gmt_created
     *
     * @param gmtCreated the value for aml_org_material_node.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_node.gmt_creator
     *
     * @return the value of aml_org_material_node.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_node.gmt_creator
     *
     * @param gmtCreator the value for aml_org_material_node.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_node.gmt_updated
     *
     * @return the value of aml_org_material_node.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_node.gmt_updated
     *
     * @param gmtUpdated the value for aml_org_material_node.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_node.gmt_updator
     *
     * @return the value of aml_org_material_node.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_node.gmt_updator
     *
     * @param gmtUpdator the value for aml_org_material_node.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_node.is_deleted
     *
     * @return the value of aml_org_material_node.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_node.is_deleted
     *
     * @param isDeleted the value for aml_org_material_node.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_node.org_material_log_id
     *
     * @return the value of aml_org_material_node.org_material_log_id
     *
     * @mbggenerated
     */
    public Integer getOrgMaterialLogId() {
        return orgMaterialLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_node.org_material_log_id
     *
     * @param orgMaterialLogId the value for aml_org_material_node.org_material_log_id
     *
     * @mbggenerated
     */
    public void setOrgMaterialLogId(Integer orgMaterialLogId) {
        this.orgMaterialLogId = orgMaterialLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_node.material_node_id
     *
     * @return the value of aml_org_material_node.material_node_id
     *
     * @mbggenerated
     */
    public Integer getMaterialNodeId() {
        return materialNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_node.material_node_id
     *
     * @param materialNodeId the value for aml_org_material_node.material_node_id
     *
     * @mbggenerated
     */
    public void setMaterialNodeId(Integer materialNodeId) {
        this.materialNodeId = materialNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_org_material_node.node_status
     *
     * @return the value of aml_org_material_node.node_status
     *
     * @mbggenerated
     */
    public String getNodeStatus() {
        return nodeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_org_material_node.node_status
     *
     * @param nodeStatus the value for aml_org_material_node.node_status
     *
     * @mbggenerated
     */
    public void setNodeStatus(String nodeStatus) {
        this.nodeStatus = nodeStatus == null ? null : nodeStatus.trim();
    }
}