package com.antimoney.boot.model;

public class RiskPrevention {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.submit_year
     *
     * @mbggenerated
     */
    private String submitYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.sys_grade
     *
     * @mbggenerated
     */
    private String sysGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.new_biz_name_SI
     *
     * @mbggenerated
     */
    private String newBizNameSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.is_participate_RA
     *
     * @mbggenerated
     */
    private Integer isParticipateRa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.dep_contribution_MI
     *
     * @mbggenerated
     */
    private String depContributionMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.anti_risk_measure_MI
     *
     * @mbggenerated
     */
    private String antiRiskMeasureMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_risk_prevention.remark_MI
     *
     * @mbggenerated
     */
    private String remarkMi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.id
     *
     * @return the value of aml_risk_prevention.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.id
     *
     * @param id the value for aml_risk_prevention.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.gmt_created
     *
     * @return the value of aml_risk_prevention.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.gmt_created
     *
     * @param gmtCreated the value for aml_risk_prevention.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.gmt_creator
     *
     * @return the value of aml_risk_prevention.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.gmt_creator
     *
     * @param gmtCreator the value for aml_risk_prevention.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.gmt_updated
     *
     * @return the value of aml_risk_prevention.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.gmt_updated
     *
     * @param gmtUpdated the value for aml_risk_prevention.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.gmt_updator
     *
     * @return the value of aml_risk_prevention.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.gmt_updator
     *
     * @param gmtUpdator the value for aml_risk_prevention.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.is_deleted
     *
     * @return the value of aml_risk_prevention.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.is_deleted
     *
     * @param isDeleted the value for aml_risk_prevention.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.submit_year
     *
     * @return the value of aml_risk_prevention.submit_year
     *
     * @mbggenerated
     */
    public String getSubmitYear() {
        return submitYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.submit_year
     *
     * @param submitYear the value for aml_risk_prevention.submit_year
     *
     * @mbggenerated
     */
    public void setSubmitYear(String submitYear) {
        this.submitYear = submitYear == null ? null : submitYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.sys_grade
     *
     * @return the value of aml_risk_prevention.sys_grade
     *
     * @mbggenerated
     */
    public String getSysGrade() {
        return sysGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.sys_grade
     *
     * @param sysGrade the value for aml_risk_prevention.sys_grade
     *
     * @mbggenerated
     */
    public void setSysGrade(String sysGrade) {
        this.sysGrade = sysGrade == null ? null : sysGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.org_id
     *
     * @return the value of aml_risk_prevention.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.org_id
     *
     * @param orgId the value for aml_risk_prevention.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.new_biz_name_SI
     *
     * @return the value of aml_risk_prevention.new_biz_name_SI
     *
     * @mbggenerated
     */
    public String getNewBizNameSi() {
        return newBizNameSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.new_biz_name_SI
     *
     * @param newBizNameSi the value for aml_risk_prevention.new_biz_name_SI
     *
     * @mbggenerated
     */
    public void setNewBizNameSi(String newBizNameSi) {
        this.newBizNameSi = newBizNameSi == null ? null : newBizNameSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.is_participate_RA
     *
     * @return the value of aml_risk_prevention.is_participate_RA
     *
     * @mbggenerated
     */
    public Integer getIsParticipateRa() {
        return isParticipateRa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.is_participate_RA
     *
     * @param isParticipateRa the value for aml_risk_prevention.is_participate_RA
     *
     * @mbggenerated
     */
    public void setIsParticipateRa(Integer isParticipateRa) {
        this.isParticipateRa = isParticipateRa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.dep_contribution_MI
     *
     * @return the value of aml_risk_prevention.dep_contribution_MI
     *
     * @mbggenerated
     */
    public String getDepContributionMi() {
        return depContributionMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.dep_contribution_MI
     *
     * @param depContributionMi the value for aml_risk_prevention.dep_contribution_MI
     *
     * @mbggenerated
     */
    public void setDepContributionMi(String depContributionMi) {
        this.depContributionMi = depContributionMi == null ? null : depContributionMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.anti_risk_measure_MI
     *
     * @return the value of aml_risk_prevention.anti_risk_measure_MI
     *
     * @mbggenerated
     */
    public String getAntiRiskMeasureMi() {
        return antiRiskMeasureMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.anti_risk_measure_MI
     *
     * @param antiRiskMeasureMi the value for aml_risk_prevention.anti_risk_measure_MI
     *
     * @mbggenerated
     */
    public void setAntiRiskMeasureMi(String antiRiskMeasureMi) {
        this.antiRiskMeasureMi = antiRiskMeasureMi == null ? null : antiRiskMeasureMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_risk_prevention.remark_MI
     *
     * @return the value of aml_risk_prevention.remark_MI
     *
     * @mbggenerated
     */
    public String getRemarkMi() {
        return remarkMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_risk_prevention.remark_MI
     *
     * @param remarkMi the value for aml_risk_prevention.remark_MI
     *
     * @mbggenerated
     */
    public void setRemarkMi(String remarkMi) {
        this.remarkMi = remarkMi == null ? null : remarkMi.trim();
    }
}