package com.antimoney.boot.model;

public class SuspiciousTransactions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.submit_year
     *
     * @mbggenerated
     */
    private String submitYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.sys_grade
     *
     * @mbggenerated
     */
    private String sysGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.org_name_SI
     *
     * @mbggenerated
     */
    private String orgNameSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.labor_division_MI
     *
     * @mbggenerated
     */
    private String laborDivisionMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.recheck_situation_MI
     *
     * @mbggenerated
     */
    private String recheckSituationMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.analyze_reason_MI
     *
     * @mbggenerated
     */
    private String analyzeReasonMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.report_description_MI
     *
     * @mbggenerated
     */
    private String reportDescriptionMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_suspicious_transactions.remark_MI
     *
     * @mbggenerated
     */
    private String remarkMi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.id
     *
     * @return the value of aml_suspicious_transactions.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.id
     *
     * @param id the value for aml_suspicious_transactions.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.gmt_created
     *
     * @return the value of aml_suspicious_transactions.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.gmt_created
     *
     * @param gmtCreated the value for aml_suspicious_transactions.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.gmt_creator
     *
     * @return the value of aml_suspicious_transactions.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.gmt_creator
     *
     * @param gmtCreator the value for aml_suspicious_transactions.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.gmt_updated
     *
     * @return the value of aml_suspicious_transactions.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.gmt_updated
     *
     * @param gmtUpdated the value for aml_suspicious_transactions.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.gmt_updator
     *
     * @return the value of aml_suspicious_transactions.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.gmt_updator
     *
     * @param gmtUpdator the value for aml_suspicious_transactions.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.is_deleted
     *
     * @return the value of aml_suspicious_transactions.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.is_deleted
     *
     * @param isDeleted the value for aml_suspicious_transactions.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.submit_year
     *
     * @return the value of aml_suspicious_transactions.submit_year
     *
     * @mbggenerated
     */
    public String getSubmitYear() {
        return submitYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.submit_year
     *
     * @param submitYear the value for aml_suspicious_transactions.submit_year
     *
     * @mbggenerated
     */
    public void setSubmitYear(String submitYear) {
        this.submitYear = submitYear == null ? null : submitYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.sys_grade
     *
     * @return the value of aml_suspicious_transactions.sys_grade
     *
     * @mbggenerated
     */
    public String getSysGrade() {
        return sysGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.sys_grade
     *
     * @param sysGrade the value for aml_suspicious_transactions.sys_grade
     *
     * @mbggenerated
     */
    public void setSysGrade(String sysGrade) {
        this.sysGrade = sysGrade == null ? null : sysGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.org_id
     *
     * @return the value of aml_suspicious_transactions.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.org_id
     *
     * @param orgId the value for aml_suspicious_transactions.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.org_name_SI
     *
     * @return the value of aml_suspicious_transactions.org_name_SI
     *
     * @mbggenerated
     */
    public String getOrgNameSi() {
        return orgNameSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.org_name_SI
     *
     * @param orgNameSi the value for aml_suspicious_transactions.org_name_SI
     *
     * @mbggenerated
     */
    public void setOrgNameSi(String orgNameSi) {
        this.orgNameSi = orgNameSi == null ? null : orgNameSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.labor_division_MI
     *
     * @return the value of aml_suspicious_transactions.labor_division_MI
     *
     * @mbggenerated
     */
    public String getLaborDivisionMi() {
        return laborDivisionMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.labor_division_MI
     *
     * @param laborDivisionMi the value for aml_suspicious_transactions.labor_division_MI
     *
     * @mbggenerated
     */
    public void setLaborDivisionMi(String laborDivisionMi) {
        this.laborDivisionMi = laborDivisionMi == null ? null : laborDivisionMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.recheck_situation_MI
     *
     * @return the value of aml_suspicious_transactions.recheck_situation_MI
     *
     * @mbggenerated
     */
    public String getRecheckSituationMi() {
        return recheckSituationMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.recheck_situation_MI
     *
     * @param recheckSituationMi the value for aml_suspicious_transactions.recheck_situation_MI
     *
     * @mbggenerated
     */
    public void setRecheckSituationMi(String recheckSituationMi) {
        this.recheckSituationMi = recheckSituationMi == null ? null : recheckSituationMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.analyze_reason_MI
     *
     * @return the value of aml_suspicious_transactions.analyze_reason_MI
     *
     * @mbggenerated
     */
    public String getAnalyzeReasonMi() {
        return analyzeReasonMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.analyze_reason_MI
     *
     * @param analyzeReasonMi the value for aml_suspicious_transactions.analyze_reason_MI
     *
     * @mbggenerated
     */
    public void setAnalyzeReasonMi(String analyzeReasonMi) {
        this.analyzeReasonMi = analyzeReasonMi == null ? null : analyzeReasonMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.report_description_MI
     *
     * @return the value of aml_suspicious_transactions.report_description_MI
     *
     * @mbggenerated
     */
    public String getReportDescriptionMi() {
        return reportDescriptionMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.report_description_MI
     *
     * @param reportDescriptionMi the value for aml_suspicious_transactions.report_description_MI
     *
     * @mbggenerated
     */
    public void setReportDescriptionMi(String reportDescriptionMi) {
        this.reportDescriptionMi = reportDescriptionMi == null ? null : reportDescriptionMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_suspicious_transactions.remark_MI
     *
     * @return the value of aml_suspicious_transactions.remark_MI
     *
     * @mbggenerated
     */
    public String getRemarkMi() {
        return remarkMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_suspicious_transactions.remark_MI
     *
     * @param remarkMi the value for aml_suspicious_transactions.remark_MI
     *
     * @mbggenerated
     */
    public void setRemarkMi(String remarkMi) {
        this.remarkMi = remarkMi == null ? null : remarkMi.trim();
    }
}