package com.antimoney.boot.model;

public class TransferReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.gmt_created
     *
     * @mbggenerated
     */
    private String gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.gmt_creator
     *
     * @mbggenerated
     */
    private String gmtCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.gmt_updated
     *
     * @mbggenerated
     */
    private String gmtUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.gmt_updator
     *
     * @mbggenerated
     */
    private String gmtUpdator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.submit_year
     *
     * @mbggenerated
     */
    private String submitYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.sys_grade
     *
     * @mbggenerated
     */
    private String sysGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.org_name_SI
     *
     * @mbggenerated
     */
    private String orgNameSi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.transfer_details_MI
     *
     * @mbggenerated
     */
    private String transferDetailsMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.transfer_time_DI
     *
     * @mbggenerated
     */
    private String transferTimeDi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.report_time_DI
     *
     * @mbggenerated
     */
    private String reportTimeDi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.report_method_MI
     *
     * @mbggenerated
     */
    private String reportMethodMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aml_transfer_report.remark_MI
     *
     * @mbggenerated
     */
    private String remarkMi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.id
     *
     * @return the value of aml_transfer_report.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.id
     *
     * @param id the value for aml_transfer_report.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.gmt_created
     *
     * @return the value of aml_transfer_report.gmt_created
     *
     * @mbggenerated
     */
    public String getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.gmt_created
     *
     * @param gmtCreated the value for aml_transfer_report.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(String gmtCreated) {
        this.gmtCreated = gmtCreated == null ? null : gmtCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.gmt_creator
     *
     * @return the value of aml_transfer_report.gmt_creator
     *
     * @mbggenerated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.gmt_creator
     *
     * @param gmtCreator the value for aml_transfer_report.gmt_creator
     *
     * @mbggenerated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.gmt_updated
     *
     * @return the value of aml_transfer_report.gmt_updated
     *
     * @mbggenerated
     */
    public String getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.gmt_updated
     *
     * @param gmtUpdated the value for aml_transfer_report.gmt_updated
     *
     * @mbggenerated
     */
    public void setGmtUpdated(String gmtUpdated) {
        this.gmtUpdated = gmtUpdated == null ? null : gmtUpdated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.gmt_updator
     *
     * @return the value of aml_transfer_report.gmt_updator
     *
     * @mbggenerated
     */
    public String getGmtUpdator() {
        return gmtUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.gmt_updator
     *
     * @param gmtUpdator the value for aml_transfer_report.gmt_updator
     *
     * @mbggenerated
     */
    public void setGmtUpdator(String gmtUpdator) {
        this.gmtUpdator = gmtUpdator == null ? null : gmtUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.is_deleted
     *
     * @return the value of aml_transfer_report.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.is_deleted
     *
     * @param isDeleted the value for aml_transfer_report.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.submit_year
     *
     * @return the value of aml_transfer_report.submit_year
     *
     * @mbggenerated
     */
    public String getSubmitYear() {
        return submitYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.submit_year
     *
     * @param submitYear the value for aml_transfer_report.submit_year
     *
     * @mbggenerated
     */
    public void setSubmitYear(String submitYear) {
        this.submitYear = submitYear == null ? null : submitYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.sys_grade
     *
     * @return the value of aml_transfer_report.sys_grade
     *
     * @mbggenerated
     */
    public String getSysGrade() {
        return sysGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.sys_grade
     *
     * @param sysGrade the value for aml_transfer_report.sys_grade
     *
     * @mbggenerated
     */
    public void setSysGrade(String sysGrade) {
        this.sysGrade = sysGrade == null ? null : sysGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.org_id
     *
     * @return the value of aml_transfer_report.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.org_id
     *
     * @param orgId the value for aml_transfer_report.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.org_name_SI
     *
     * @return the value of aml_transfer_report.org_name_SI
     *
     * @mbggenerated
     */
    public String getOrgNameSi() {
        return orgNameSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.org_name_SI
     *
     * @param orgNameSi the value for aml_transfer_report.org_name_SI
     *
     * @mbggenerated
     */
    public void setOrgNameSi(String orgNameSi) {
        this.orgNameSi = orgNameSi == null ? null : orgNameSi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.transfer_details_MI
     *
     * @return the value of aml_transfer_report.transfer_details_MI
     *
     * @mbggenerated
     */
    public String getTransferDetailsMi() {
        return transferDetailsMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.transfer_details_MI
     *
     * @param transferDetailsMi the value for aml_transfer_report.transfer_details_MI
     *
     * @mbggenerated
     */
    public void setTransferDetailsMi(String transferDetailsMi) {
        this.transferDetailsMi = transferDetailsMi == null ? null : transferDetailsMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.transfer_time_DI
     *
     * @return the value of aml_transfer_report.transfer_time_DI
     *
     * @mbggenerated
     */
    public String getTransferTimeDi() {
        return transferTimeDi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.transfer_time_DI
     *
     * @param transferTimeDi the value for aml_transfer_report.transfer_time_DI
     *
     * @mbggenerated
     */
    public void setTransferTimeDi(String transferTimeDi) {
        this.transferTimeDi = transferTimeDi == null ? null : transferTimeDi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.report_time_DI
     *
     * @return the value of aml_transfer_report.report_time_DI
     *
     * @mbggenerated
     */
    public String getReportTimeDi() {
        return reportTimeDi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.report_time_DI
     *
     * @param reportTimeDi the value for aml_transfer_report.report_time_DI
     *
     * @mbggenerated
     */
    public void setReportTimeDi(String reportTimeDi) {
        this.reportTimeDi = reportTimeDi == null ? null : reportTimeDi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.report_method_MI
     *
     * @return the value of aml_transfer_report.report_method_MI
     *
     * @mbggenerated
     */
    public String getReportMethodMi() {
        return reportMethodMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.report_method_MI
     *
     * @param reportMethodMi the value for aml_transfer_report.report_method_MI
     *
     * @mbggenerated
     */
    public void setReportMethodMi(String reportMethodMi) {
        this.reportMethodMi = reportMethodMi == null ? null : reportMethodMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aml_transfer_report.remark_MI
     *
     * @return the value of aml_transfer_report.remark_MI
     *
     * @mbggenerated
     */
    public String getRemarkMi() {
        return remarkMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aml_transfer_report.remark_MI
     *
     * @param remarkMi the value for aml_transfer_report.remark_MI
     *
     * @mbggenerated
     */
    public void setRemarkMi(String remarkMi) {
        this.remarkMi = remarkMi == null ? null : remarkMi.trim();
    }
}