package com.antimoney.boot.mapper;

import com.antimoney.boot.model.amlInternalControlRegulation;

public interface amlInternalControlRegulationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int insert(amlInternalControlRegulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int insertSelective(amlInternalControlRegulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    amlInternalControlRegulation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(amlInternalControlRegulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(amlInternalControlRegulation record);
}