package com.antimoney.boot.mapper;

import com.antimoney.boot.model.AmlInternalControlRegulation;
import org.springframework.stereotype.Service;

@Service
public interface AmlInternalControlRegulationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int insert(AmlInternalControlRegulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int insertSelective(AmlInternalControlRegulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    AmlInternalControlRegulation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmlInternalControlRegulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_submit_log_and_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmlInternalControlRegulation record);
}