package com.antimoney.boot.mapper;

import com.antimoney.boot.model.AttachmentType;

public interface AttachmentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_attachment_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_attachment_type
     *
     * @mbggenerated
     */
    int insert(AttachmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_attachment_type
     *
     * @mbggenerated
     */
    int insertSelective(AttachmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_attachment_type
     *
     * @mbggenerated
     */
    AttachmentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_attachment_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AttachmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_attachment_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AttachmentType record);
}