package com.antimoney.boot.mapper;

import com.antimoney.boot.model.EvaluationItem;

public interface EvaluationItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_evaluation_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_evaluation_item
     *
     * @mbggenerated
     */
    int insert(EvaluationItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_evaluation_item
     *
     * @mbggenerated
     */
    int insertSelective(EvaluationItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_evaluation_item
     *
     * @mbggenerated
     */
    EvaluationItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_evaluation_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EvaluationItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_evaluation_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EvaluationItem record);
}