package com.antimoney.boot.mapper;

import com.antimoney.boot.model.LeadingGroupConference;

public interface LeadingGroupConferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_leading_group_conference
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_leading_group_conference
     *
     * @mbggenerated
     */
    int insert(LeadingGroupConference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_leading_group_conference
     *
     * @mbggenerated
     */
    int insertSelective(LeadingGroupConference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_leading_group_conference
     *
     * @mbggenerated
     */
    LeadingGroupConference selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_leading_group_conference
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LeadingGroupConference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_leading_group_conference
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LeadingGroupConference record);
}