package com.antimoney.boot.mapper;

import com.antimoney.boot.model.MaterialType;

public interface MaterialTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_type
     *
     * @mbggenerated
     */
    int insert(MaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_type
     *
     * @mbggenerated
     */
    int insertSelective(MaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_type
     *
     * @mbggenerated
     */
    MaterialType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MaterialType record);
}