package com.antimoney.boot.mapper;

import com.antimoney.boot.model.MaterialNode;

public interface MaterialNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_node
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_node
     *
     * @mbggenerated
     */
    int insert(MaterialNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_node
     *
     * @mbggenerated
     */
    int insertSelective(MaterialNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_node
     *
     * @mbggenerated
     */
    MaterialNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_node
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MaterialNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_material_node
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MaterialNode record);
}