package com.antimoney.boot.mapper;

import com.antimoney.boot.model.OrgMaterialLog;

public interface OrgMaterialLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_log
     *
     * @mbggenerated
     */
    int insert(OrgMaterialLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_log
     *
     * @mbggenerated
     */
    int insertSelective(OrgMaterialLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_log
     *
     * @mbggenerated
     */
    OrgMaterialLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgMaterialLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgMaterialLog record);
}