package com.antimoney.boot.mapper;

import com.antimoney.boot.model.OrgMaterialNode;

public interface OrgMaterialNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_node
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_node
     *
     * @mbggenerated
     */
    int insert(OrgMaterialNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_node
     *
     * @mbggenerated
     */
    int insertSelective(OrgMaterialNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_node
     *
     * @mbggenerated
     */
    OrgMaterialNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_node
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgMaterialNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_org_material_node
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgMaterialNode record);
}