package com.antimoney.boot.mapper;

import com.antimoney.boot.model.RiskPrevention;

public interface RiskPreventionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_risk_prevention
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_risk_prevention
     *
     * @mbggenerated
     */
    int insert(RiskPrevention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_risk_prevention
     *
     * @mbggenerated
     */
    int insertSelective(RiskPrevention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_risk_prevention
     *
     * @mbggenerated
     */
    RiskPrevention selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_risk_prevention
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RiskPrevention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_risk_prevention
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RiskPrevention record);
}