package com.antimoney.boot.mapper;

import com.antimoney.boot.model.SuspiciousTransactions;

public interface SuspiciousTransactionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_suspicious_transactions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_suspicious_transactions
     *
     * @mbggenerated
     */
    int insert(SuspiciousTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_suspicious_transactions
     *
     * @mbggenerated
     */
    int insertSelective(SuspiciousTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_suspicious_transactions
     *
     * @mbggenerated
     */
    SuspiciousTransactions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_suspicious_transactions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SuspiciousTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aml_suspicious_transactions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SuspiciousTransactions record);
}